##Tarefa 5.1 - Pré-processamento de um conjunto de dados

1- Ler a variável e armazenar como dataframe

In [1]:
!git clone "https://github.com/malegopc/DSBD"

Cloning into 'DSBD'...
remote: Enumerating objects: 531, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 531 (delta 28), reused 74 (delta 28), pack-reused 457
Receiving objects: 100% (531/531), 9.43 MiB | 17.66 MiB/s, done.
Resolving deltas: 100% (236/236), done.


In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv ('DSBD/Datasets/Churn/Churn_Modelling_2.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

2- Eliminar linhas com dados ausentes de IsActivemember

In [3]:
df.dropna(subset=['IsActiveMember'],inplace = False)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[9986 rows x 14 columns]

3 - Faça a imputação dos dados ausentes para a variável "NumOfProducts" utilizando a média da variável.

In [4]:
from sklearn.impute import SimpleImputer
import numpy as np
df2 = df.copy()
imputer = SimpleImputer(missing_values = np.nan, strategy ='median')
df2[["NumOfProducts"]] = imputer.fit_transform(df2[["NumOfProducts"]].values)

df2.isnull().sum()

RowNumber           0
CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
NumOfProducts       0
HasCrCard           0
IsActiveMember     14
EstimatedSalary     0
Exited              0
dtype: int64

4 - Crie uma variável (array) X que contenha os valores apenas dos atributos/colunas de "CreditScore" a "EstimatedSalary" utilizando a função "iloc" do Pandas. Em outras palavras, crie uma variável X que receba o dataframe inteiro exceto as 3 primeiras colunas e a última. Observe que as 3 primeiras colunas "RowNumber", "CustomerId" e "Surname" não são importantes e devem ser descartadas. E a última coluna ("Exited") será a variável destino ("target" ou saída) que será criada no próximo passo;

In [5]:
dfx = df.iloc[: , 3:12]
print(dfx)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00            1.0   
1             608     Spain  Female   41       1   83807.86            1.0   
2             502    France  Female   42       8  159660.80            3.0   
3             699    France  Female   39       1       0.00            2.0   
4             850     Spain  Female   43       2  125510.82            1.0   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00            2.0   
9996          516    France    Male   35      10   57369.61            1.0   
9997          709    France  Female   36       7       0.00            1.0   
9998          772   Germany    Male   42       3   75075.31            2.0   
9999          792    France  Female   28       4  130142.79            1.0   

      HasCrCard  IsActiveMember  
0             1             1

5 - Crie uma variável (array) y que contenha apenas a última coluna  ("Exited"). Esta é a variável destino ("target" ou saída);

In [6]:
dfy = df.iloc[:,-1]
print(dfy)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64


6 - Codifique a coluna/variável categórica "Geography" como numérica utilizando a classe LabelEncoder da biblioteca scikit-learn;

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
lg=le.fit_transform(dfx.Geography)
lg

array([0, 2, 0, ..., 0, 1, 0])

In [8]:
dfx['x'] = lg
dfx

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00            1.0   
1             608     Spain  Female   41       1   83807.86            1.0   
2             502    France  Female   42       8  159660.80            3.0   
3             699    France  Female   39       1       0.00            2.0   
4             850     Spain  Female   43       2  125510.82            1.0   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00            2.0   
9996          516    France    Male   35      10   57369.61            1.0   
9997          709    France  Female   36       7       0.00            1.0   
9998          772   Germany    Male   42       3   75075.31            2.0   
9999          792    France  Female   28       4  130142.79            1.0   

      HasCrCard  IsActiveMember  x  
0             1             1.0  0  
1             0             1.0  2  
2             1             0.0  0  
3             0             0.0  0  
4             1             1.0  2  
...         ...             ... ..  
9995          1             0.0  0  
9996          1             1.0  0  
9997          0             1.0  0  
9998          1             0.0  1  
9999          1             0.0  0  

[10000 rows x 10 columns]

In [9]:
dfx = dfx[[	'CreditScore',	'Geography','x','Gender',	'Age',	'Tenure',	'Balance',	'NumOfProducts',	'HasCrCard',	'IsActiveMember']]
dfx

CreditScore Geography  x  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  0  Female   42       2       0.00            1.0   
1             608     Spain  2  Female   41       1   83807.86            1.0   
2             502    France  0  Female   42       8  159660.80            3.0   
3             699    France  0  Female   39       1       0.00            2.0   
4             850     Spain  2  Female   43       2  125510.82            1.0   
...           ...       ... ..     ...  ...     ...        ...            ...   
9995          771    France  0    Male   39       5       0.00            2.0   
9996          516    France  0    Male   35      10   57369.61            1.0   
9997          709    France  0  Female   36       7       0.00            1.0   
9998          772   Germany  1    Male   42       3   75075.31            2.0   
9999          792    France  0  Female   28       4  130142.79            1.0   

      HasCrCard  IsActiveMember  
0             1             1.0  
1             0             1.0  
2             1             0.0  
3             0             0.0  
4             1             1.0  
...         ...             ...  
9995          1             0.0  
9996          1             1.0  
9997          0             1.0  
9998          1             0.0  
9999          1             0.0  

[10000 rows x 10 columns]

7 - Codifique a coluna/variável categórica "Gender" como numérica utilizando a classe LabelEncoder da biblioteca scikit-learn;

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
lge=le.fit_transform(dfx.Gender)
lge

array([0, 0, 0, ..., 0, 1, 0])

In [11]:
dfx['G'] = lge
dfx

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


CreditScore Geography  x  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  0  Female   42       2       0.00            1.0   
1             608     Spain  2  Female   41       1   83807.86            1.0   
2             502    France  0  Female   42       8  159660.80            3.0   
3             699    France  0  Female   39       1       0.00            2.0   
4             850     Spain  2  Female   43       2  125510.82            1.0   
...           ...       ... ..     ...  ...     ...        ...            ...   
9995          771    France  0    Male   39       5       0.00            2.0   
9996          516    France  0    Male   35      10   57369.61            1.0   
9997          709    France  0  Female   36       7       0.00            1.0   
9998          772   Germany  1    Male   42       3   75075.31            2.0   
9999          792    France  0  Female   28       4  130142.79            1.0   

      HasCrCard  IsActiveMember  G  
0             1             1.0  0  
1             0             1.0  0  
2             1             0.0  0  
3             0             0.0  0  
4             1             1.0  0  
...         ...             ... ..  
9995          1             0.0  1  
9996          1             1.0  1  
9997          0             1.0  0  
9998          1             0.0  1  
9999          1             0.0  0  

[10000 rows x 11 columns]

In [12]:
dfx = dfx[['Geography','x','CreditScore','Gender','G',	'Age',	'Tenure',	'Balance',	'NumOfProducts',	'HasCrCard',	'IsActiveMember']]
dfx

Geography  x  CreditScore  Gender  G  Age  Tenure    Balance  \
0       France  0          619  Female  0   42       2       0.00   
1        Spain  2          608  Female  0   41       1   83807.86   
2       France  0          502  Female  0   42       8  159660.80   
3       France  0          699  Female  0   39       1       0.00   
4        Spain  2          850  Female  0   43       2  125510.82   
...        ... ..          ...     ... ..  ...     ...        ...   
9995    France  0          771    Male  1   39       5       0.00   
9996    France  0          516    Male  1   35      10   57369.61   
9997    France  0          709  Female  0   36       7       0.00   
9998   Germany  1          772    Male  1   42       3   75075.31   
9999    France  0          792  Female  0   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  
0               1.0          1             1.0  
1               1.0          0             1.0  
2               3.0          1             0.0  
3               2.0          0             0.0  
4               1.0          1             1.0  
...             ...        ...             ...  
9995            2.0          1             0.0  
9996            1.0          1             1.0  
9997            1.0          0             1.0  
9998            2.0          1             0.0  
9999            1.0          1             0.0  

[10000 rows x 11 columns]

Pra melhor vizualização, criei uma nova coluna com os valores convertidos de variável categórica para numérica no exercício 6 e 7

8 - Após executar o passo 6, transforme os dados da variável "Geography" para a forma binária utilizando a classe OneHotEncoder da biblioteca scikit-learn eliminando redundância, ou seja, aplicando a codificação de variáveis dummy. Observe que há apenas 3 países (categorias) diferentes.

In [13]:
from sklearn.preprocessing import OneHotEncoder
ohc = OneHotEncoder()
arr = ohc.fit_transform(dfx[['x']]).toarray()
arr

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [14]:
arraydf = pd.DataFrame(arr)
print(arraydf)

        0    1    2
0     1.0  0.0  0.0
1     0.0  0.0  1.0
2     1.0  0.0  0.0
3     1.0  0.0  0.0
4     0.0  0.0  1.0
...   ...  ...  ...
9995  1.0  0.0  0.0
9996  1.0  0.0  0.0
9997  1.0  0.0  0.0
9998  0.0  1.0  0.0
9999  1.0  0.0  0.0

[10000 rows x 3 columns]


In [15]:
finaldf = arraydf.join(dfx)
finaldf

0    1    2 Geography  x  CreditScore  Gender  G  Age  Tenure  \
0     1.0  0.0  0.0    France  0          619  Female  0   42       2   
1     0.0  0.0  1.0     Spain  2          608  Female  0   41       1   
2     1.0  0.0  0.0    France  0          502  Female  0   42       8   
3     1.0  0.0  0.0    France  0          699  Female  0   39       1   
4     0.0  0.0  1.0     Spain  2          850  Female  0   43       2   
...   ...  ...  ...       ... ..          ...     ... ..  ...     ...   
9995  1.0  0.0  0.0    France  0          771    Male  1   39       5   
9996  1.0  0.0  0.0    France  0          516    Male  1   35      10   
9997  1.0  0.0  0.0    France  0          709  Female  0   36       7   
9998  0.0  1.0  0.0   Germany  1          772    Male  1   42       3   
9999  1.0  0.0  0.0    France  0          792  Female  0   28       4   

        Balance  NumOfProducts  HasCrCard  IsActiveMember  
0          0.00            1.0          1             1.0  
1      83807.86            1.0          0             1.0  
2     159660.80            3.0          1             0.0  
3          0.00            2.0          0             0.0  
4     125510.82            1.0          1             1.0  
...         ...            ...        ...             ...  
9995       0.00            2.0          1             0.0  
9996   57369.61            1.0          1             1.0  
9997       0.00            1.0          0             1.0  
9998   75075.31            2.0          1             0.0  
9999  130142.79            1.0          1             0.0  

[10000 rows x 14 columns]

Não entendi muito bem a proposta de ter apenas 2 colunas, uma vez em que temos 3 países, decidi deixar as colunas 0,1,2 e também a coluna x pra você ver que deu certo. Além de deixar a coluna Geography pra um melhor entendimento. 

9 - Divida as variáveis X e y em dados de treino e de teste utilizando o método "train_test_split", gerando as variáveis X_train, X_test, y_train e y_test. Você define a proporção de dados de treino e de teste;

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dfx,dfy,test_size=0.5,random_state=0)
print(X_train.shape)
print(X_test.shape)

(5000, 11)
(5000, 11)


10-Faça a padronização (escalonamento) dos dados das variáveis X_train e X_test utilizando a classe StandardScaler do scikit-learn;

In [17]:
X_train

Geography  x  CreditScore  Gender  G  Age  Tenure    Balance  \
333    Germany  1          584  Female  0   30       8  112013.81   
6391    France  0          726  Female  0   38       5  126875.62   
4786    France  0          577  Female  0   34       2       0.00   
357      Spain  2          522    Male  1   34       9  126436.29   
9854     Spain  2          681  Female  0   37       6  121231.39   
...        ... ..          ...     ... ..  ...     ...        ...   
9225   Germany  1          594  Female  0   32       4  120074.97   
4859     Spain  2          794  Female  0   22       4  114440.24   
3264    France  0          738    Male  1   35       5  161274.05   
9845     Spain  2          590  Female  0   38       9       0.00   
2732   Germany  1          623  Female  0   48       1  108076.33   

      NumOfProducts  HasCrCard  IsActiveMember  
333             1.0          1             0.0  
6391            1.0          1             0.0  
4786            2.0          1             1.0  
357             1.0          1             0.0  
9854            1.0          1             1.0  
...             ...        ...             ...  
9225            2.0          1             1.0  
4859            1.0          1             1.0  
3264            2.0          1             0.0  
9845            2.0          1             1.0  
2732            1.0          1             0.0  

[5000 rows x 11 columns]

In [18]:
training_set = X_train.iloc[:, 1:2].values # coluna 1
print(training_set)
print(training_set.shape)

[[1]
 [0]
 [0]
 ...
 [0]
 [2]
 [1]]
(5000, 1)


In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(training_set)
training_set_scaled = sc.transform(training_set)
print("Média dos dados originais",sc.mean_)
print("Variância dos dados originais",sc.var_)
#padronização de geography

Média dos dados originais [0.7404]
Variância dos dados originais [0.68540784]


In [20]:
print("Média dos dados escalonados: ",round(training_set_scaled.mean()))
print("Variância dos dados escalonados: ",round(training_set_scaled.var()))

Média dos dados escalonados:  0
Variância dos dados escalonados:  1


------------------------- Gender-------------

In [21]:
training_set12 = X_train.iloc[:, 4:5].values # coluna 1
print(training_set12)
print(training_set12.shape)

[[0]
 [0]
 [0]
 ...
 [1]
 [0]
 [0]]
(5000, 1)


In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(training_set12)
training_set_scaledgender = sc.transform(training_set12)
print("Média dos dados originais",sc.mean_)
print("Variância dos dados originais",sc.var_)
#padronização de gender

Média dos dados originais [0.5432]
Variância dos dados originais [0.24813376]


In [23]:
print("Média dos dados escalonados: ",round(training_set_scaledgender.mean()))
print("Variância dos dados escalonados: ",round(training_set_scaledgender.var()))

Média dos dados escalonados:  0
Variância dos dados escalonados:  1


##Tarefa 5.2  Aplicação de diferentes algoritmos de AM numa tarefa de predição (classificação) Churn

1 -  Você deve aplicar os seguintes algoritmos de AM:
      ° Regressão Lógica:

In [27]:
from sklearn import metrics
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver = 'liblinear') # liblinear => conjuntos pequenos
logreg.fit(X_train,y_train)
classificacoes_logreg = logreg.predict(X_test)
acertos_LogReg = metrics.accuracy_score(y_test,classificacoes_logreg)
print('Taxa de acerto = ',round(acertos_LogReg*100,2),"%\n")
# matriz de confusão
print('Matriz de confusão:\n')
cm_logreg = ConfusionMatrixDisplay.from_estimator(logreg, X_test, y_test)
#print(cm_logreg.confusion_matrix)
plt.show()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


ValueError: ignored